
services:
  mongo-db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    container_name: products
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "mongo-db"
      - "rabbitmq"
    volumes:
      - ./:./app
      - /app/products/node_modules
    
    env_file:
      - ./products/.env.dev

  customers:
    build:
      context: ./customers
      dockerfile: Dockerfile
    container_name: customers
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "mongo-db"
      - "rabbitmq"
    volumes:
      - ./:./app
      - /app/customers/node_modules
    
    env_file:
      - ./customers/.env.dev

  shopping:
    build:
      context: ./shopping
      dockerfile: Dockerfile
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "mongo-db"
      - "rabbitmq"
    volumes:
      - ./:./app
      - /app/shopping/node_modules
    
    env_file:
      - ./shopping/.env.dev

  nginx-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - products
      - customers
      - shopping
    ports:
      - 80:80